version: '3.8'

services:
  # База данных
  main-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: testing_system
      POSTGRES_USER: main_module
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - main_postgres_data:/var/lib/postgresql/data
      - ./main-module/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main_module -d testing_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Главный модуль
  main-module:
    build:
      context: ./main-module
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      DB_HOST: main-postgres
      DB_PORT: 5432
      DB_NAME: testing_system
      DB_USER: main_module
      DB_PASSWORD: secret123
      SERVER_PORT: 3002
      JWT_SECRET: test_secret
    depends_on:
      main-postgres:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  main_postgres_data:
