events {}

http {
  resolver 127.0.0.11 valid=10s;

  upstream bot_logic {
    zone bot_logic 64k;
    server bot-logic:3005;
  }

  server {
    listen 8080;

    location /api/telegram/ {
      proxy_pass http://bot_logic;
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
      proxy_pass http://bot_logic/health;
    }
  }
}
